# Help Page
http_request:


online_image:
  - url: "http://esphome-web-678334.local:8081/"
    format: jpg
    id: my_online_image
    update_interval: 1

lvgl:
  pages:
    - id: page_help
      bg_color: col_black
      widgets:
        - image:
            id: my_online_image_img
            x: 50
            y: 50 
            src: my_online_image
        - label:
            id: lbl_A_pg_help
            text_color: col_white
            text_font: roboto
            text: "Press \U000F0B08 for Alarm \U000F0734"
            align: TOP_RIGHT
            y: 20
        - label:
            id: lbl_B_pg_help        
            text_color: col_white
            text_font: roboto
            text: "Press \U000F0B09 for Electricity \U000F0734"
            align: TOP_MID        
            align_to: 
              id: lbl_A_pg_help
              align: OUT_BOTTOM_RIGHT
              y: 40
        - label:
            id: lbl_C_pg_help        
            text_color: col_white
            text_font: roboto
            text: "Press \U000F0B0A for Button \U000F0734"
            align: TOP_MID        
            align_to: 
              id: lbl_B_pg_help
              align: OUT_BOTTOM_RIGHT
              y: 40
        - label:
            id: lbl_D_pg_help        
            text_color: col_white
            text_font: roboto
            text: "Press \U000F0B0B for Weather \U000F0734"
            align: TOP_MID        
            align_to: 
              id: lbl_C_pg_help
              align: OUT_BOTTOM_RIGHT
              y: 40
  