#Control(Button) Page

lvgl:
  pages:
    - id: pageC
      bg_color: col_black
      widgets:
        - obj:
            id: lvgl_keypad_obj
            width: 100%
            height: 100%
            hidden: false
            bg_color: col_black
            outline_width: 0
            border_width: 0
            pad_all: 0
            widgets:      
              - buttonmatrix:
                  id: lvgl_keypad
                  width: 100%
                  height: 100%
                  items:
                    pressed:
                      bg_color: 0xFFFF00
                  rows:
                    - buttons:
                        - text: "1\n\U000F0335\nTanes"
                          id: lvgl_keypad_button1
                          control:
                            no_repeat: true
                            checkable: true
                          on_press:
                            switch.toggle: tanes_lights                
                        - text: "2\n\U000F0335\nFront"
                          id: lvgl_keypad_button2
                          control:
                            no_repeat: true
                            checkable: true
                          on_press:
                            switch.toggle: front_lights                  
                        - text: "3\n\U000F0335\nKitchen"
                          id: lvgl_keypad_button3
                          control:
                            no_repeat: true
                            checkable: true
                          on_press:
                            switch.toggle: kitchen_lights                      
                    - buttons:
                        - text: "4\n\U000F1A2B\nTanes"
                          id: lvgl_keypad_button4
                          control:
                            no_repeat: true
                            checkable: true
                        - text: "5\n\U000F1A2B\nLucys"
                          id: lvgl_keypad_button5
                          control:
                            no_repeat: true
                            checkable: true
                        - text: "6\n\U000F1A2B\nStudy"
                          id: lvgl_keypad_button6
                          control:
                            no_repeat: true
                            checkable: true
                    - buttons:
                        - text: "7\n\U000F001B\nKids"
                          id: lvgl_keypad_button7
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            switch.toggle: kids_ac
                        - text: "8\n\U000F001B\nMaster"
                          id: lvgl_keypad_button8
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            switch.toggle: master_ac
                        - text: "9\n\U000F0606\nPool"
                          id: lvgl_keypad_button9
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            switch.toggle: pool_switch
                    - buttons:
                        - text: "*\n\U000F00DF\nScreen"
                          id: lvgl_keypad_button_star
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            light.toggle: Backlight
                        - text: "0\n\U000F05F1\nEV"
                          id: lvgl_keypad_button0
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            switch.toggle: EV_switch
                        - text: "#\n\U000F04A1\nStairs"
                          id: lvgl_keypad_button_hash
                          key_code: "#"
                          control:
                            no_repeat: true
                            checkable: true
                          on_click:
                            switch.toggle: stairs_sign
        - obj:
            id: lvgl_thermostat_obj
            width: 100%
            height: 100%
            hidden: true
            bg_color: col_red
            bg_grad_color: col_blue
            bg_grad_dir: ver                
            outline_width: 0
            border_width: 0
            pad_all: 0
            scrollbar_mode: "OFF"     
         
            widgets:
              - obj:
                  id: lvgl_thermostat_top_obj
                  width: 100%
                  height: 50%              
                  align: TOP_MID
                  border_width: 0    
                  scrollbar_mode: "OFF"   
                  bg_opa: 50%
                  blur_backdrop: true
                  widgets:  
                    - arc:
                        id: ch_setpoint_arc_top
                        align: CENTER
                        y: 10
                        adjustable: true
                        value: 22
                        min_value: 10
                        max_value: 35
                        width: 210
                        height: 210
                        arc_width: 16
                        arc_color: 0x292929
                        indicator:
                          arc_color: 0xFF6F22
                          arc_width: 16
                        knob:
                          bg_color: 0xFFFFFF
                    - label:
                        id: ch_action_label_top
                        align: CENTER
                        y: -40
                        text: "--"
                        text_font: roboto_sml
                    - label:
                        id: ch_setpoint_label_top
                        align: CENTER
                        text: "--.-°"
                        y: 0
                        text_font: roboto_lrg
                    - label:
                        id: ch_temperature_label_top
                        align: CENTER
                        text: "--.-°"
                        text_color: 0xFF6F22
                        y: 50               
                        text_font: roboto_sml
                    - label:
                        id: ch_mode_label_top
                        align: CENTER
                        y: 90
                        text: "OFF"
                        border_color: 0xFFFFFF
                        border_width: 1
                        pad_top: 2
                        pad_bottom: 2
                        pad_left: 8
                        pad_right: 8
                        text_font: roboto_sml
              - obj:
                  id: lvgl_thermostat_bottom_obj
                  width: 100%
                  height: 50%              
                  align: BOTTOM_MID
                  border_width: 0    
                  bg_opa: 50%
                  blur_backdrop: true
                  scrollbar_mode: "OFF"   
                  widgets:  
                    - arc:
                        id: ch_setpoint_arc_bottom
                        align: CENTER
                        y: 10
                        adjustable: true
                        value: 50
                        min_value: 50
                        max_value: 300
                        width: 210
                        height: 210
                        arc_width: 16
                        arc_color: 0x292929
                        indicator:
                          arc_color: 0xFF6F22
                          arc_width: 16
                        knob:
                          bg_color: 0xFFFFFF
                    - label:
                        id: ch_action_label_bottom
                        align: CENTER
                        y: -40
                        text_font: montserrat_14
                        text: "--"
                    - label:
                        id: ch_setpoint_label_bottom
                        align: CENTER
                        text: "--.-°"
                        y: 0
                        text_font: montserrat_48
                    - label:
                        id: ch_temperature_label_bottom
                        align: CENTER
                        text: "--.-°"
                        text_font: montserrat_24
                        text_color: 0xFF6F22
                        y: 50               
                    - label:
                        id: ch_mode_label_bottom
                        align: CENTER
                        y: 90
                        text_font: montserrat_14
                        text: "OFF"
                        border_color: 0xFFFFFF
                        border_width: 1
                        pad_top: 2
                        pad_bottom: 2
                        pad_left: 8
                        pad_right: 8
              