#Control(Button) Page

lvgl:
  pages:
    - id: pageC
      bg_color: col_black
      widgets:
        - buttonmatrix:
            id: lvgl_keypad
            width: 100%
            height: 100%
            items:
              pressed:
                bg_color: 0xFFFF00
            rows:
              - buttons:
                  - text: "1\n\_\_\U000F0335\nTanes"
                    id: lvgl_keypad_button1
                    control:
                      no_repeat: true
                      checkable: true
                    on_press:
                      switch.toggle: tanes_lights                
                  - text: "2\n\_\_\U000F0335\nFront"
                    id: lvgl_keypad_button2
                    control:
                      no_repeat: true
                      checkable: true
                    on_press:
                      switch.toggle: front_lights                  
                  - text: "3\n\_\_\_\U000F0335\nKitchen"
                    id: lvgl_keypad_button3
                    control:
                      no_repeat: true
                      checkable: true
                    on_press:
                      switch.toggle: kitchen_lights                      
              - buttons:
                  - text: "4\n\U000F1A2B\nTanes"
                    id: lvgl_keypad_button4
                    control:
                      no_repeat: true
                      checkable: true
                  - text: "5\n\U000F1A2B\nLucys"
                    id: lvgl_keypad_button5
                    control:
                      no_repeat: true
                      checkable: true
                  - text: "6\n\U000F1A2B\nStudy"
                    id: lvgl_keypad_button6
                    control:
                      no_repeat: true
                      checkable: true
              - buttons:
                  - text: "7\n\U000F001B\nKids"
                    id: lvgl_keypad_button7
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: kids_ac
                  - text: "8\n\U000F001B\nMaster"
                    id: lvgl_keypad_button8
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: master_ac
                  - text: "9\n\U000F0606\nPool"
                    id: lvgl_keypad_button9
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: pool_switch
              - buttons:
                  - text: "*\n\U000F1466\nDehumid"
                    id: lvgl_keypad_button_star
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: dehumidifier_switch
                  - text: "0\n\U000F05F1\nEV"
                    id: lvgl_keypad_button0
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: EV_switch
                  - text: "#\n\U000F04A1\nStairs"
                    id: lvgl_keypad_button_hash
                    key_code: "#"
                    control:
                      no_repeat: true
                      checkable: true
                    on_click:
                      switch.toggle: stairs_sign
