lvgl:
  - pages:
    - id: pageA
      bg_color: col_black
      widgets:
        - label:
            id: lbl_title_pgA
            text_color: col_yellow
            text_font: roboto_lrg
            text: "Alarm"
            align: TOP_MID
        - label:
            id: img_alarm_icon        
            text_color: col_white
            text_font: icons_200
            text: "\U000F02D6"
            align: TOP_MID        
            align_to: 
              id: lbl_tittle
              align: OUT_BOTTOM_MID
        - textarea:
            id: lbl_status
            text_color: col_gray
            text_font: roboto_lrg
            bg_color: col_black
            one_line: true   
            text_align: CENTER
            text: "Loading..."
            align: TOP_MID    
            border_width: 0
            cursor:
              bg_opa: transp       
              opa: transp 
            align_to: 
              id: img_alarm_icon
              align: OUT_BOTTOM_MID         
        - textarea:
            id: txt_passcode
            one_line: true       
            placeholder_text: "Enter code"   
            text_align: CENTER
            width: 45%
            align_to:         
              id: lbl_status
              align: OUT_BOTTOM_MID   
              y: 40      

