- id: pageA
  bg_color: col_black
  widgets:
    - label:
        id: lbl_title_pgA
        text_color: col_yellow
        text_font: roboto_lrg
        text: "Alarm!"
        align: TOP_MID
        border_width: 2    
        border_side: INTERNAL            
    - label:
        id: img_alarm_icon        
        width: 270
        height: 270
        text_color: col_white
        text_font: icons_200
        text: "\U000F009A"
        align: TOP_MID        
        align_to: 
          id: lbl_tittle
          align: OUT_BOTTOM_MID
     
    

