color:
  - id: col_blue
    hex: 0000ff
  - id: col_red
    hex: ff0000
  - id: col_green
    hex: 00ff00
  - id: col_dkgreen
    hex: 008800    
  - id: col_white
    hex: ffffff
  - id: col_yellow
    hex: ffff00   
  - id: col_orange
    hex: FFA500   
  - id: col_gray
    hex: 6f6f6f   
  - id: col_black
    red:   0.0000
    green: 0.0000
    blue:  0.0000
    white: 0.0000


font:
  - file: "gfonts://Roboto"

    id: roboto_lrg
    size: 50
    glyphs: '?|!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'   
  - file: "gfonts://Roboto"
    id: roboto
    size: 25
    glyphs: '*#¢$/|!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
    extras:
      - file: "fonts/materialdesignicons-webfont.ttf"
        glyphs: [
          "\U000F0335", # mdi-lightbulb
          "\U000F1A2B", # mdi-blinds-horizontal
          "\U000F001B", # mdi-air-conditioner
          ]
  - file: "gfonts://Roboto"
    id: roboto_sml
    size: 12
    glyphs: '/’–|!?"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'    
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_200
    size: 200
    bpp: 4
    glyphs: [
      "\U000F02D6", # help (?)
      "\U000F009A", # bell  
      "\U000F009B", # bell-off  
      "\U000F009E", # bell-ring
      "\U000F0596", # pouring
      "\U000F0590", # cloudy
      "\U000F0594", # clear-night
      "\U000F0898", # weather-hurricane
      "\U000F0F30", # weather-hazy
      "\U000F0599", # sunny
      "\U000F0F33", # weather-partly-rainy
      "\U000F0595", # partlycloudy
      "\U000F0597", # rainy
      "\U000F059D", # windy
      "\U000F0598", # snowy
      "\U000F067E", # lightning-rainy
      "\U000F0591", # fog
      "\U000F12CB", # snowflake-melt
      "\U000F0F2F"
    ]