
web_server:
  port: 80
  
globals:
  - id: g_keypad
    type: std::string
    restore_value: no
    max_restore_data_length: 5
    initial_value: ''


time:
  - platform: homeassistant
    id: homeassistant_time    

output:
  - id: backlight_output
    platform: gpio
    pin: GPIO25

light:
  - platform: binary
    name: "Display Backlight"
    id: Backlight
    restore_mode: ALWAYS_ON
    output: backlight_output

sensor:
    # Wifi Signal
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 300s
    entity_category: "diagnostic"
    internal: true
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    id: wifi_signal_pct
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic" 
    
    #debug
  - platform: debug
    free:
      name: "Heap Free"
      id: HeapFree
    block:
      name: "Heap Max Block"
      id: HeapMaxBlock
    loop_time:
      name: "Loop Time"
      id: LoopTime
    psram:
      name: "Free PSRAM"
      id: freePSRAM     
  - platform: internal_temperature
    name: "Internal Temperature" 
    id: InternalTemp   


  - platform: uptime
    type: seconds
    id: uptime_sensor
    name: uptime_sensor
    filters:
      - lambda: return x / 86400;
    unit_of_measurement: "d"
    entity_category: "diagnostic" 
    accuracy_decimals: 5
    

binary_sensor: 
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      ignore_strapping_warning: true
    name: "Onboard button"
    id: onboard_button
    on_press:
      - script.execute: script_pageC_blinds
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadA
    key: A
    on_press:
      - lvgl.page.show: pageA
      - script.execute: script_page_carousel
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadB
    key: B
    on_press:
    - lvgl.page.show: pageB
    - script.execute: script_page_carousel
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadC
    key: C
    on_press:
      - lvgl.page.show: pageC
      - script.execute: script_page_carousel
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadD
    key: D
    on_press:
      - lvgl.page.show: pageD
      - script.execute: script_page_carousel


touchscreen:
  platform: xpt2046
#needs calibration
  calibration:
    x_min: 150
    x_max: 3950
    y_min: 250
    y_max: 3960 
  id: my_touchscreen
  spi_id: touch_spi
  cs_pin: GPIO22
  interrupt_pin: GPIO01
  transform: 
    mirror_y: true
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );


#ST7796 display
spi:
  - id: display_spi
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: 
      number: GPIO12
      ignore_strapping_warning: true 
  - id: touch_spi
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19 


display:
  - platform: ili9xxx
    model: ST7796
    id: my_display
    invert_colors: false    
    spi_id: display_spi
    dc_pin: GPIO27
    reset_pin: GPIO33
    cs_pin: 
      number: GPIO15
      ignore_strapping_warning: true 
    dimensions:  #320x480 only possible with psram
      width: 320
      height: 480

    color_palette: NONE 
    data_rate: 80MHz
    auto_clear_enabled: false
    update_interval: never
    # pages: !include_dir_merge_list alarm-panel/display_pages/

 
lvgl:
  id: !extend lvgl_display
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  text_font: roboto
  theme:
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 5
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x001015  
