matrix_keypad:
  id: keypad
  columns:
    - pin: 
        number: GPIO35
        mode: 
          input: True
    - pin: 
        number: GPIO34
        mode: 
          input: True
    - pin: 
        number: GPIO39
        mode: 
          input: True
    - pin: 
        number: GPIO36
        mode: 
          input: True  
  rows:
    - pin: 
        number: GPIO02
        mode: 
          output: True  
        ignore_strapping_warning: true  
    - pin:  
        number: GPIO04
        mode: 
          output: True 
    - pin:  
        number: GPIO21
        mode: 
          output: True     
    - pin:  
        number: GPIO05
        mode: 
          output: True  
        ignore_strapping_warning: true             
  keys: "123A456B789C*0#D"
  has_diodes: false  
  
          
    