matrix_keypad:
  id: keypad
  columns:
    - pin: 
        number: GPIO35
        mode: 
          input: True
    - pin: 
        number: GPIO34
        mode: 
          input: True
    - pin: 
        number: GPIO39
        mode: 
          input: True
    - pin: 
        number: GPIO36
        mode: 
          input: True  
  rows:
    - pin: 
        number: GPIO02
        mode: 
          output: True  
        ignore_strapping_warning: true  
    - pin:  
        number: GPIO04
        mode: 
          output: True 
    - pin:  
        number: GPIO21
        mode: 
          output: True     
    - pin:  
        number: GPIO05
        mode: 
          output: True  
        ignore_strapping_warning: true             
  keys: "123A456B789C*0#D"
  has_diodes: false  
  
key_collector:
  - id: pincode_reader
    source_id: keypad
    end_keys: "#"
    end_key_required: true 
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 60s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
      - globals.set:
          id: g_keypad
          value: !lambda "return (x.c_str());"          
    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
      - globals.set:
          id: g_keypad
          value: !lambda "return (x.c_str());"    
      - if:
          condition:
            # Checks if "homeassistant_alarm" has state "disarmed" arm else disarm
            text_sensor.state:
              id: homeassistant_alarm
              state: 'disarmed'   
          then:
            homeassistant.service: 
              service: script.alarm_arm
              data:
                code: !lambda "return (x.c_str());"   
          else:
            homeassistant.service: 
              service: script.alarm_disarm
              data:
                code: !lambda "return (x.c_str());"             
    