binary_sensor: 
  - platform: touchscreen
    id: touch_button_1a
    x_min: 0
    x_max: 80
    y_min: 0
    y_max: 80
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: switch.sonoff_10007724b9      
  - platform: touchscreen
    id: touch_button_1b
    x_min: 80
    x_max: 160
    y_min: 0
    y_max: 80
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: switch.sonoff_10007724b9      
  - platform: touchscreen
    id: touch_button_1c
    x_min: 160
    x_max: 240
    y_min: 0
    y_max: 80
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: switch.sonoff_10001adcce       
  - platform: touchscreen
    id: touch_button_1d
    x_min: 240
    x_max: 360
    y_min: 0
    y_max: 80
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: switch.sonoff_10001adcce    

  - platform: touchscreen
    id: touch_button_2a
    x_min: 0
    x_max: 80
    y_min: 80
    y_max: 160
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.open_cover
          data_template:
            entity_id: cover.carrington_rd     
      - homeassistant.service:
          service: cover.open_cover
          data_template:
            entity_id: cover.darri_ave           
  - platform: touchscreen
    id: touch_button_2b
    x_min: 80
    x_max: 160
    y_min: 80
    y_max: 160
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.close_cover
          data_template:
            entity_id: cover.carrington_rd     
      - homeassistant.service:
          service: cover.close_cover
          data_template:
            entity_id: cover.darri_ave              
  - platform: touchscreen
    id: touch_button_2c
    x_min: 160
    x_max: 240
    y_min: 80
    y_max: 160
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: input_boolean.car_charger_override 
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: switch.sonoff_100155a107_2                  
  - platform: touchscreen
    id: touch_button_2d
    x_min: 240
    x_max: 360
    y_min: 80
    y_max: 160
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: input_boolean.car_charger_override 
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: switch.sonoff_100155a107_2                             


  - platform: touchscreen
    id: touch_button_3a
    x_min: 0
    x_max: 80
    y_min: 160
    y_max: 240
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.open_cover
          data_template:
            entity_id: cover.study     
  - platform: touchscreen
    id: touch_button_3b
    x_min: 80
    x_max: 160
    y_min: 160
    y_max: 240
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.close_cover
          data_template:
            entity_id: cover.study           
  - platform: touchscreen
    id: touch_button_3c
    x_min: 160
    x_max: 240
    y_min: 160
    y_max: 240
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.open_cover
          data_template:
            entity_id: cover.tane
  - platform: touchscreen
    id: touch_button_3d
    x_min: 240
    x_max: 360
    y_min: 160
    y_max: 240
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: cover.close_cover
          data_template:
            entity_id: cover.tane                           


  - platform: touchscreen
    id: touch_button_4a
    x_min: 0
    x_max: 80
    y_min: 240
    y_max: 320
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: media_player.turn_on
          data_template:
            entity_id: media_player.lounge_av_reciever
  - platform: touchscreen
    id: touch_button_4b
    x_min: 80
    x_max: 160
    y_min: 240
    y_max: 320
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: media_player.turn_off
          data_template:
            entity_id: media_player.lounge_av_reciever    
  - platform: touchscreen
    id: touch_button_4c
    x_min: 160
    x_max: 240
    y_min: 240
    y_max: 320
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: switch.sonoff_100155a107_2
      - homeassistant.service:
          service: switch.turn_on
          data_template:
            entity_id: input_boolean.car_charger_override
  - platform: touchscreen
    id: touch_button_4d
    x_min: 240
    x_max: 360
    y_min: 240
    y_max: 320
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: switch.sonoff_100155a107_2                        
      - homeassistant.service:
          service: switch.turn_off
          data_template:
            entity_id: input_boolean.car_charger_override


  - platform: touchscreen
    id: touch_button_5a
    x_min: 0
    x_max: 80
    y_min: 320
    y_max: 400
    page_id: pageC      
    on_press:
      - homeassistant.service:
          service: light.turn_on
          data_template:
            entity_id: light.lucy_top_bunk
            brightness_pct: '10' 
  - platform: touchscreen
    id: touch_button_5b
    x_min: 80
    x_max: 160
    y_min: 320
    y_max: 400
    page_id: pageC      
    on_press:
     - homeassistant.service:
        service: light.turn_on
        data:
          brightness_step_pct: '100'
          entity_id: light.lucy_top_bunk
  - platform: touchscreen
    id: touch_button_5c
    x_min: 160
    x_max: 240
    y_min: 320
    y_max: 400
    page_id: pageC    
    on_press:
      - homeassistant.service:
          service: light.turn_off
          data_template:
            entity_id: light.lucy_top_bunk
  - platform: touchscreen
    id: touch_button_5d
    x_min: 240
    x_max: 360
    y_min: 320
    y_max: 400
    page_id: pageC      
    #on_press:
         

  - platform: touchscreen
    name: 6A Touch Button
    id: touch_button_6a
    x_min: 0
    x_max: 80
    y_min: 400
    y_max: 480
    page_id: pageC      
    #on_press:
  - platform: touchscreen
    name: 6B Touch Button
    id: touch_button_6b
    x_min: 80
    x_max: 160
    y_min: 400
    y_max: 480
    page_id: pageC      
    #on_press:
  - platform: touchscreen
    name: 6C Touch Button
    id: touch_button_6c
    x_min: 160
    x_max: 240
    y_min: 400
    y_max: 480
    page_id: pageC    
    #on_press:
  - platform: touchscreen
    id: touch_button_6d
    name: 6D Touch Button
    x_min: 240
    x_max: 360
    y_min: 400
    y_max: 480
    page_id: pageC      
    #on_press:
         