script:
  - id: script_page_carousel
    mode: restart
    then:
        - delay: 30s    #wait for sensors etc to be ready 
        - while:
            condition:
                - wifi.connected:
            then:
                - display.page.show: pageA                     
                - delay: 5 min              
                - while:
                    condition:
                        - text_sensor.state:
                            id: homeassistant_alarm
                            state: 'disarmed'                        
                    then:
                        - display.page.show: pageB
                        - delay: 10s
                        - display.page.show: pageC
                        - delay: 2s
                        - display.page.show: pageD
                        - delay: 8s      
                        - display.page.show: pageD2
                        - delay: 7s  
                        - display.page.show: pageD3
                        - delay: 7s 
        - display.page.show: pageA           
