script:
  - id: script_page_carousel
    mode: restart
    then:
        - delay: 30s    #wait for sensors etc to be ready 
        - while:
            condition:
                - wifi.connected:
            then:
                - delay: 5 min              
                - while:
                    condition:
                        - text_sensor.state:
                            id: homeassistant_alarm
                            state: 'disarmed'                        
                    then:
                        - lvgl.page.show: page_help
                        - if:
                            condition:
                                lambda: 'return id(uptime_sensor).state < 1;'
                            then:
                                - delay: 10s   
                        - if:
                            condition:
                                lambda: 'return id(uptime_sensor).state < 3;'
                            then:
                                - delay: 4s   
                        - if:
                            condition:
                                lambda: 'return id(uptime_sensor).state < 7;'
                            then:
                                - delay: 3s  
                        - delay: 3s  
                        - lvgl.page.show: pageB
                        - delay: 10s
                        - lvgl.page.show: pageC
                        - delay: 2s
                        - lvgl.page.show: pageD
                        - delay: 8s  
        - lvgl.page.show: pageA           


#  to manage state of blinds as mysmartblinds status unreliable
  - id: script_pageC_blinds
    mode: queued 
    max_runs: 3
    then:
      - delay: 30s    #wait for sensors etc to be ready

      #Study
      - logger.log:
          format: "The blind study reports value %.1f to script"
          args: [ 'id(blind_study).state' ]   
      - if:
          condition:
            lambda: return isnan(id(blind_study).state);
          then:
            - logger.log:
                format: "no blind state so using The sun state. value %s "
                args: [ 'id(sun).state.c_str()' ] 
            - if:
                condition:
                  lambda: 'return id(sun).state == "below_horizon";'
                then:
                  - logger.log: "blind_study sun set. set blind close"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: true    
                else:
                  - logger.log: "blind_study sun up. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: false    
          else:
            - if:
                condition:
                  sensor.in_range:
                    id: blind_study
                    above: 10.0
                    below: 90.0
                then:
                  - logger.log: "blind_study range closed. set blind closed"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: true    
                else:              
                  - logger.log: "blind_study range open. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: false
    
      #Lucys
      - logger.log:
          format: "The blind_lucy1 reports value %.1f and %.1f to script"
          args: [ 'id(blind_lucy1).state', 'id(blind_lucy2).state'  ]   
      - if:
          condition:
            lambda: return isnan(id(blind_lucy1).state);
          then:
            - logger.log:
                format: "no blind state so using The sun state. value %s "
                args: [ 'id(sun).state.c_str()' ] 
            - if:
                condition:
                  lambda: 'return id(sun).state == "below_horizon";'
                then:
                  - logger.log: "blind_study sun set. set blind close"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: true    
                else:
                  - logger.log: "blind_study sun up. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: false    
          else:
            - if:
                condition:
                  or:
                    - sensor.in_range:
                        id: blind_lucy1
                        above: 10.0
                        below: 90.0
                    - sensor.in_range:
                        id: blind_lucy
                        above: 10.0
                        below: 90.0
                then:
                  - logger.log: "blind_study range closed. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: false    
                else:              
                  - logger.log: "blind_study range open. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: true      

      #tane
      - logger.log:
          format: "The blind_tane reports value %.1f to script"
          args: [ 'id(blind_tane).state' ]   
      - if:
          condition:
            lambda: return isnan(id(blind_tane).state);
          then:
            - logger.log:
                format: "no blind state so using The sun state. value %s "
                args: [ 'id(sun).state.c_str()' ] 
            - if:
                condition:
                  lambda: 'return id(sun).state == "below_horizon";'
                then:
                  - logger.log: "blind_study sun set. set blind close"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: true    
                else:
                  - logger.log: "blind_study sun up. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: false    
          else:
            - if:
                condition:
                  sensor.in_range:
                    id: blind_tane
                    above: 10.0
                    below: 90.0
                then:
                  - logger.log: "blind_tane range closed. set blind closed"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: true    
                else:              
                  - logger.log: "blind_tane range open. set blind open"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: false    

      - logger.log:
          format: "The blind_lucy1 reports value %.1f to script"
          args: [ 'id(blind_lucy1).state' ]   
      - logger.log:
          format: "The blind_lucy2 reports value %.1f to script"
          args: [ 'id(blind_lucy2).state' ]   
      - logger.log:
          format: "The blind_tane reports value %.1f to script"
          args: [ 'id(blind_tane).state' ]          
      - delay: 1min
