script:
  - id: script_page_carousel
    mode: restart
    then:
        - delay: 30s    #wait for sensors etc to be ready 
        - while:
            condition:
                - wifi.connected:
            then:
                - delay: 5 min              
                - while:
                    condition:
                        - text_sensor.state:
                            id: homeassistant_alarm
                            state: 'disarmed'                        
                    then:
                        - lvgl.page.show: page_help
                        - if:
                            condition:
                            lambda: 'return id(uptime_sensor) < 1'
                            then:
                                - delay: 10s   
                        - if:
                            condition:
                            lambda: 'return id(uptime_sensor) < 3'
                            then:
                                - delay: 4s   
                        - if:
                            condition:
                            lambda: 'return id(uptime_sensor) < 7'
                            then:
                                - delay: 3s  
                        - delay: 3s  
                        - lvgl.page.show: pageB
                        - delay: 10s
                        - lvgl.page.show: pageC
                        - delay: 2s
                        - lvgl.page.show: pageD
                        - delay: 8s  
        - lvgl.page.show: pageA           
