substitutions:
  name: esphome-web-8d4831
  friendly_name: alarm-panel-master
  inside_temp: sensibo_Master_Bedroom_Temperature
  outside_temp: outside_balcony_temp_humidity_temperature


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  on_boot:
    - priority: 800
      then:
        - logger.log: "Device ready"
        - script.execute: script_page_carousel 
        - script.execute: script_pageC_blinds

  project:
    name: "nilbogAus.esphome-alarm-panel"
    version: "2.0.0"

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true
   # version: recommended
    # Custom sdkconfig options
    sdkconfig_options:  
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:      

# Enable logging
logger:
  level: DEBUG
#  level: WARN
  logs:
    component: ERROR  # To disable "Component display took a long time for an operation (0.09 s)."

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome-web-9d4d29_api_encryption_key

# Allow Over-The-Air updates
ota:
  password: !secret esphome-web-9d4d29_ota_password
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

debug:
  update_interval: 300s

lvgl:
  id: lvgl_display

packages:
  remote_package_files:  
    url: https://github.com/nilbogAus/esphome-alarm-panel/
    path: ESPHome/alarm-panel
    files: 
      - path: main.yaml
      - path: assets.yaml
      - path: matrix_keypad.yaml
      - path: scripts.yaml
    ref: main
    refresh: 5s
  remote_package_files2:  
    url: https://github.com/nilbogAus/esphome-alarm-panel/
    path: ESPHome/alarm-panel/LVGL_ctrl/
    files:       
      - path: PageActrl.yaml
      - path: PageBctrl.yaml
      - path: PageCctrl.yaml
      - path: PageDctrl.yaml
    ref: main
    refresh: 5s
  remote_package_files3:  
    url: https://github.com/nilbogAus/esphome-alarm-panel/
    path: ESPHome/alarm-panel/LVGL_pages/
    files:       
      - path: pageA.yaml
      - path: pageB.yaml
      - path: pageC.yaml
      - path: pageD.yaml
      - path: page_help
    ref: main
    refresh: 5s    
  remote_package_files4:  
    url: https://github.com/nilbogAus/esphome-alarm-panel/
    path: ESPHome/alarm-panel/Displays/
    files:       
      #- path: XMKJ3-95_4-0.yaml
      #- path: EQV4-0inchLCD.yaml
      - path: ECBuyingTFTColorScreen.yaml
    ref: main
    refresh: 5s    
    


