substitutions:
  name: esphome-web-8d4831
  friendly_name: alarm-panel-master

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
   # version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_PERFORMANCE: y    

# Enable logging
logger:
  level: debug
#  level: WARN
  logs:
    component: ERROR  # To disable "Component display took a long time for an operation (0.09 s)."

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome-web-9d4d29_api_encryption_key

# Allow Over-The-Air updates
ota:
  password: !secret esphome-web-9d4d29_ota_password
  platform: esphome
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret esphome-web-9d4d29_wifi_ap_password

captive_portal:

packages:
  assets: !include alarm-panel/assets.yaml   
  matrix_keypad: !include alarm-panel/matrix_keypad.yaml
  #my_scripts: !include alarm-panel/scripts.yaml
 # PageC: !include alarm-panel/PageCbuttons.yaml  

globals:
  - id: g_keypad
    type: std::string
    restore_value: no
    max_restore_data_length: 5
    initial_value: ''

debug:
  update_interval: 300s

switch:
  - platform: homeassistant
    id: pool_switch
    entity_id: switch.sonoff_10001e7f40

  - platform: homeassistant
    id: ryobi_batteries_switch
    entity_id: switch.sonoff_10001e9d60

  - platform: homeassistant
    id: refrigerator_express_mode
    entity_id: switch.refrigerator_express_mode


text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      id: DeviceInfo
    reset_reason:
      name: "Reset Reason"   

  - platform: homeassistant
    name: "Alarm State"
    id: homeassistant_alarm
    entity_id: alarm_control_panel.home_alarm 

  - platform: homeassistant
    name: "Pool Cleaner"
    id: pool_cleaner
    entity_id: sensor.creepy_status

  - platform: homeassistant
    name: "Forecast Today Text"
    id: forecast_text_today
    entity_id: sensor.wahroonga_extended_text_0
  - platform: homeassistant
    name: "Forecast Today Rain Chance"
    id: forecast_rain_chance_today
    entity_id: sensor.wahroonga_rain_chance_0
  - platform: homeassistant
    name: "Forecast Today Icon"
    id: forecast_icon_today
    entity_id: sensor.wahroonga_mdi_icon_0
  - platform: homeassistant
    name: "Forecast Today label"
    id: forecast_label_today
    entity_id: sensor.wahroonga_now_now_label    

  - platform: homeassistant
    name: "Forecast Text"
    id: forecast_text
    entity_id: sensor.wahroonga_extended_text_1
  - platform: homeassistant
    name: "Forecast Rain Chance"
    id: forecast_rain_chance
    entity_id: sensor.wahroonga_rain_chance_1
  - platform: homeassistant
    name: "Forecast Icon"
    id: forecast_icon
    entity_id: sensor.wahroonga_mdi_icon_1    

  - platform: homeassistant
    name: "Forecast Text"
    id: forecast_text_2
    entity_id: sensor.wahroonga_extended_text_2
  - platform: homeassistant
    name: "Forecast Rain Chance"
    id: forecast_rain_chance_2
    entity_id: sensor.wahroonga_rain_chance_2
  - platform: homeassistant
    name: "Forecast Icon"
    id: forecast_icon_2
    entity_id: sensor.wahroonga_mdi_icon_2  


time:
  - platform: homeassistant
    id: homeassistant_time    

output:
  - id: backlight_output
    platform: gpio
    pin: GPIO25

light:
  - platform: binary
    name: "Display Backlight"
    id: Backlight
    restore_mode: ALWAYS_ON
    output: backlight_output

sensor:
    # Wifi Signal
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 300s
    entity_category: "diagnostic"
    internal: true
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    id: wifi_signal_pct
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic" 
    
    #debug
  - platform: debug
    free:
      name: "Heap Free"
      id: HeapFree
    block:
      name: "Heap Max Block"
      id: HeapMaxBlock
    loop_time:
      name: "Loop Time"
      id: LoopTime
    psram:
      name: "Free PSRAM"
      id: freePSRAM     
  - platform: internal_temperature
    name: "Internal Temperature" 
    id: InternalTemp   

  - platform: homeassistant
    name: "Net Power state"
    id: net_power
    entity_id: sensor.net_power
  - platform: homeassistant
    name: "Home Battery Power"
    id: home_battery_power
    entity_id: sensor.encharge_492334007623_power      
  - platform: homeassistant
    name: "EV Power"
    id: ev_power
    entity_id: sensor.sonoff_100155a107_power_2
  - platform: homeassistant
    name: "Solar Power"
    id: solar_power
    entity_id: sensor.envoy_122348003312_current_power_production
  - platform: homeassistant
    name: "Inside Temp"
    id: inside_temp
    entity_id: sensor.adjusted_lounge_temperature
  - platform: homeassistant
    name: "Outside Temp"
    id: outside_temp
    entity_id: sensor.easyweatherv1_6_5_outdoor_temperature

  - platform: homeassistant
    name: "Forecast Temp Min"
    id: forecast_temp_min
    entity_id: sensor.wahroonga_temp_min_1
  - platform: homeassistant
    name: "Forecast Temp Max"
    id: forecast_temp_max
    entity_id: sensor.wahroonga_temp_max_1    
  - platform: homeassistant
    name: "Forecast Rain Amount Max"
    id: forecast_rain_amount_max
    entity_id: sensor.wahroonga_rain_amount_max_1
  - platform: homeassistant
    name: "Forecast Rain Amount Min"
    id: forecast_rain_amount_min
    entity_id: sensor.wahroonga_rain_amount_min_1       

  - platform: homeassistant
    name: "Forecast Today Temp Min"
    id: forecast_temp_min_today
    entity_id: sensor.wahroonga_temp_min_0
  - platform: homeassistant
    name: "Forecast Today Temp Max"
    id: forecast_temp_max_today
    entity_id: sensor.wahroonga_temp_max_0    
  - platform: homeassistant
    name: "Forecast Today Rain Amount Max"
    id: forecast_rain_amount_max_today
    entity_id: sensor.wahroonga_rain_amount_max_0
  - platform: homeassistant
    name: "Forecast Today Rain Amount Min"
    id: forecast_rain_amount_min_today
    entity_id: sensor.wahroonga_rain_amount_min_0       

  - platform: homeassistant
    name: "Forecast Temp Min"
    id: forecast_temp_min_2
    entity_id: sensor.wahroonga_temp_min_2
  - platform: homeassistant
    name: "Forecast Temp Max"
    id: forecast_temp_max_2
    entity_id: sensor.wahroonga_temp_max_2   
  - platform: homeassistant
    name: "Forecast Rain Amount Max"
    id: forecast_rain_amount_max_2
    entity_id: sensor.wahroonga_rain_amount_max_2
  - platform: homeassistant
    name: "Forecast Rain Amount Min"
    id: forecast_rain_amount_min_2
    entity_id: sensor.wahroonga_rain_amount_min_2       


#ST7796 display
spi:
  - id: display_spi
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: 
      number: GPIO12
      ignore_strapping_warning: true 
  - id: touch_spi
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO19 

display:
  - platform: ili9xxx
    model: ST7796
    id: my_display
    spi_id: display_spi
    dc_pin: GPIO27
    reset_pin: GPIO33
    cs_pin: 
      number: GPIO15
      ignore_strapping_warning: true 
    dimensions:  #320x480 only possible with psram
      width: 320
      height: 480
    rotation: 0
    color_palette: NONE 
    data_rate: 80MHz
    auto_clear_enabled: false
    update_interval: never
    # pages: !include_dir_merge_list alarm-panel/display_pages/

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  text_font: roboto
  pages: !include_dir_merge_list alarm-panel/LVGL_pages/
 

 

binary_sensor: 
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      ignore_strapping_warning: true
    name: "Onboard button"
    id: onboard_button

  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadA
    key: A
    on_press:
      - lvgl.page.show: pageA
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadB
    key: B
    on_press:
      - lvgl.page.show: pageB
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadC
    key: C
    on_press:
      - lvgl.page.show: pageC
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypadD
    key: D
    on_press:
      - lvgl.page.show: pageD


graph:
  - id: InternalTemp_graph
    duration: 24h
    width: 320 
    height: 150
    x_grid: 6h
    y_grid: 10 
    border: false
    max_range: 65
    min_range: 40
    traces:
      - sensor: InternalTemp
        color: col_red    
        continuous: true   
  - id: wifi_graph
    duration: 24h
    width: 320 
    height: 150
    x_grid: 6h
    y_grid: 10 
    max_range: 100
    min_range: 1
    border: false
    traces:
      - sensor: wifi_signal_pct
        color: col_green      
        continuous: true   
  - id: LoopTime_graph
    duration: 24h
    width: 320 
    height: 150
    x_grid: 6h
    y_grid: 10 
    border: false
    traces:
      - sensor: LoopTime
        color: col_blue           
  - id: solar_power_graph
    duration: 12h
    width: 320 
    height: 100
    x_grid: 2h
    y_grid: 2.500
    max_range: 10.000
    min_range: 10.000    
    min_value: 0     
    border: True
    traces:
      - sensor: solar_power
        color: col_green       
        line_thickness: 1     
        continuous: true   

touchscreen:
  platform: xpt2046
#needs calibration
  calibration:
    x_min: 150
    x_max: 3950
    y_min: 250
    y_max: 3960 
  id: my_touchscreen
  spi_id: touch_spi
  cs_pin: GPIO22
  interrupt_pin: GPIO01
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );
