switch:
  - platform: homeassistant
    entity_id: switch.sonoff_10007724b9
    id: tanes_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: true    
