#Weather Page
globals:
  - id: g_ForcastDay
    type: int
    restore_value: no
    initial_value: '0'

sensor:
  # Temperature
  - platform: homeassistant
    name: "Inside Temp"
    id: inside_temp
    entity_id: sensor.${inside_temp}
    on_value:
      - lvgl.label.update:
          id: lbl_inside_temp
          text: 
            format: "%.1f°C"
            args: ['id(inside_temp).get_state()']
  - platform: homeassistant
    name: "Outside Temp"
    id: outside_temp
    entity_id: sensor.${outside_temp}
    on_value:
      - lvgl.label.update:
          id: lbl_outside_temp
          text: 
            format: "%.1f°C"
            args: ['id(outside_temp).get_state()']    
  - platform: homeassistant
    name: "Right Extra Temp"
    id: Extra_temp_right
    entity_id: sensor.${extra_temp_right}
    on_value:
      - lvgl.label.update:
          id: lbl_Extra_temps_Right
          text: 
            format: "%.1f°C"
            args: ['id(Extra_temp_right).get_state()']   
      - lvgl.widget.show: wg_Extra_temps_Right
  - platform: homeassistant
    name: "Left Extra Temp"
    id: Extra_temp_left
    entity_id: sensor.${extra_temp_left}
    on_value:
      - lvgl.label.update:
          id: lbl_Extra_temps_Left
          text: 
            format: "%.1f°C"
            args: ['id(Extra_temp_left).get_state()']   
      - lvgl.widget.show: wg_Extra_temps_Left

#forcast 
  - platform: homeassistant
    name: "Forecast Today Temp Min"
    id: forecast_temp_today
    entity_id: sensor.wahroonga_now_temp_now
    on_value:   
      - lvgl.label.update:
          id: lbl_weather_text_temp
          text:
            format: "%s %.0f°C"
            args: [ 'id(forecast_label_today).state.c_str()','id(forecast_temp_today).state' ]      

  - platform: homeassistant
    name: "Forecast Today Rain Amount Max"
    id: forecast_rain_amount_max_today
    entity_id: sensor.wahroonga_rain_amount_max_0
    on_value:    
      - lvgl.label.update:
          id: lbl_weather_text_rain
          text:
            format: "%.0f to %.0fmm"
            args: [ 'id(forecast_rain_amount_min_today).state','id(forecast_rain_amount_max_today).state' ]          
  - platform: homeassistant
    name: "Forecast Today Rain Amount Min"
    id: forecast_rain_amount_min_today
    entity_id: sensor.wahroonga_rain_amount_min_0       
    on_value:
      - lvgl.label.update:
          id: lbl_weather_text_rain
          text:
            format: "%.0f to %.0fmm"
            args: [ 'id(forecast_rain_amount_min_today).state','id(forecast_rain_amount_max_today).state' ]          

text_sensor:
  - platform: homeassistant
    id: forecast_text_today
    entity_id: sensor.wahroonga_extended_text_0
    on_value:
      - lvgl.label.update:
          id: lbl_weather_longtext
          text: !lambda "return (x);"       

  - platform: homeassistant
    name: "Forecast Today Rain Chance"
    id: forecast_rain_chance_today
    entity_id: sensor.wahroonga_rain_chance_0
    on_value:
      - lvgl.label.update:
          id: lbl_rain
          text:
            format: "%s%s chance of rain"
            args: [ 'id(forecast_rain_chance_today).state.c_str()', '"%"' ]  
  - platform: homeassistant
    name: "Forecast Today label"
    id: forecast_label_today
    entity_id: sensor.wahroonga_now_now_label

  - platform: homeassistant
    name: "Forecast Today Icon"
    id: forecast_icon_today
    entity_id: sensor.wahroonga_mdi_icon_0
    on_value:
      - lvgl.label.update:
          id: lbl_weather_icon
          text: !lambda |-
            std::hash<std::string> hasher;

            switch (hasher(id(forecast_icon_today).state.c_str()))
            {
                case 1242744452: // mdi:weather-pouring
                    return ("\U000F0596");// pouring
                    break;
                case 3309699129: // mdi:weather-cloudy
                    return ("\U000F0590");// cloudy
                    break;                
                case 2949318122: // mdi:weather-night
                    return ("\U000F0594");// clear-night
                    break;
                case 345913139: // mdi:weather-hurricane
                    return ("\U000F0898"); //weather-hurricane
                    break;     
                case 1492665726: // mdi:weather-hazy
                    return ("\U000F0F30"); //weather-hazy
                    break;
                case 3041611428: // mdi:weather-sunny
                    return ("\U000F0599");// sunny
                    break;     
                case 2562052155: // mdi:weather-partly-rainy
                case 3241844169: // mdi:weather-light-showers              
                    return ("\U000F0F33");//
                    break;
                case 3348912596: // mdi:weather-partly-cloudy
                    return ("\U000F0595"); // partlycloudy
                    break;
                case 3416433233: // mdi:weather-rainy
                    return ("\U000F0597"); // rainy
                    break; 
                case 2453884742: // mdi:weather-windy          
                    return ("\U000F059D"); // windy
                    break;
                case 3996108531: // mdi:weather-snowy
                    return ("\U000F0598"); // snowy
                    break;
                case 344035588: // mdi:weather-lightning-rainy
                    return ("\U000F067E"); // lightning-rainy
                    break;                 
                case 3167514251: // mdi:weather-fog
                    return ("\U000F0591"); // fog
                    break;
                case 1097013394: // mdi:snowflake-melt
                    return ("\U000F12CB"); // snowflake-melt
                    break;  
                default:
                    ESP_LOGD("lambda", "Unknown weather type: string %s hash %u",id(forecast_icon_today).state.c_str(), hasher(id(forecast_icon_today).state));
                    return ("\U000F0F2F");
            }             

