#Control(Button) Page

switch:
# 1st row
  - platform: homeassistant
    entity_id: switch.sonoff_10007724b9
    id: tanes_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: true    
  - platform: homeassistant
    entity_id: switch.sonoff_10001adcce
    id: front_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button2
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button2
          state: 
            checked: true    
  - platform: homeassistant
    entity_id: switch.sonoff_10015acdb5
    id: kitchen_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button3
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button3
          state: 
            checked: true  

# 3rd row
  - platform: homeassistant
    entity_id: switch.sonoff_10001744f0
    id: kids_ac
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button7
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button7
          state: 
            checked: true              
  - platform: homeassistant
    entity_id: switch.sonoff_10001e7e08
    id: master_ac
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button8
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button8
          state: 
            checked: true  
  - platform: homeassistant
    id: pool_switch
    entity_id: light.pool_switch_9cdb57_mini_switch
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button9
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button9
          state: 
            checked: true     
            
# 4th row
  - platform: homeassistant
    entity_id: switch.sonoff_10015b43ad
    id: dehumidifier_switch
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button_star
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button_star
          state: 
            checked: true  
  - platform: homeassistant
    entity_id: switch.athom_smart_plug_v2_f12d0b_switch
    id: EV_switch
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button0
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button0
          state: 
            checked: true  
  - platform: homeassistant
    entity_id: input_boolean.car_charger_override
    id: EV_override_switch
  - platform: homeassistant
    entity_id: switch.stairs_sign
    id: stairs_sign
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button_hash
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button_hash
          state: 
            checked: true  


sensor:
  - platform: homeassistant
    entity_id: cover.study     
    attribute: current_tilt_position
    id: blind_study  
    name: blind_study
    on_value:
      - delay: 30s  
      - logger.log:
          format: "The blind_study reports value %.1f to sensor"
          args: [ 'id(blind_study).state' ]      
  - platform: homeassistant
    entity_id: cover.carrington_rd     
    attribute: current_tilt_position
    id: blind_lucy1  
    name: blind_lucy1
    on_value:
      - delay: 30s  
      - logger.log:
          format: "The blind_lucy1 reports value %.1f to sensor"
          args: [ 'id(blind_lucy1).state' ]  
  - platform: homeassistant
    entity_id: cover.darri_ave     
    attribute: current_tilt_position
    id: blind_lucy2  
    name: blind_lucy2
    on_value:
      - delay: 30s  
      - logger.log:
          format: "The blind_lucy2 reports value %.1f to sensor"
          args: [ 'id(blind_lucy2).state' ]  
  - platform: homeassistant
    entity_id: cover.tane     
    attribute: current_tilt_position
    id: blind_tane
    name: blind_tane
    on_value:
      - delay: 30s  
      - logger.log:
          format: "The blind_tane reports value %.1f to sensor"
          args: [ 'id(blind_tane).state' ]  

cover:
  - platform: template
    name: "Template Cover Study"
    id: cover_study
    lambda: |-
      if (isnan(id(blind_study).state)) {
        switch (id(g_blinds_study)) {
          case 50:
            return COVER_OPEN;
            break;
          case 0:
            return COVER_CLOSED;
          default:
            if (id(sun).state == "below_horizon") {
              return COVER_CLOSED;
            } else {
              return COVER_OPEN;
            };
            break; 
        }
      } else {
        if (id(blind_study).state < 90 && id(blind_study).state > 10) {
          return COVER_OPEN;
        } else {
          return COVER_CLOSED;
        };      
      };
    open_action:
      - homeassistant.service:
          service: cover.open_cover
          data_template:
            entity_id: cover.study  
      - globals.set:
          id: g_blinds_study
          value: '50'
    close_action:
      - homeassistant.service:
          service: cover.close_cover
          data_template:
            entity_id: cover.study  
      - globals.set:
          id: g_blinds_study
          value: 0
    optimistic: true

text_sensor:
  - platform: homeassistant
    entity_id: sun.sun
    id: sun
    on_value:
      - globals.set:
          id: g_blinds_study
          value: 999

globals:
  - id: g_blinds_study
    type: integer
    restore_value: no
    initial_value: 999
  - id: blinds_lucy_open
    type: bool
    restore_value: no
    initial_value: 'true'    
  - id: blinds_tane_open
    type: bool
    restore_value: no
    initial_value: 'true'     

binary_sensor: 
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad1
    key: 1
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: tanes_lights
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad2
    key: 2
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: front_lights
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad3
    key: 3
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: kitchen_lights
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad4
    key: 4
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            - if:
                condition:
                  lambda: 'return id(blinds_tane_open) == false;'
                then:
                  - homeassistant.service:
                      service: cover.open_cover
                      data_template:
                        entity_id: cover.tane  
                  - globals.set:
                      id: blinds_tane_open
                      value: 'true'  
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: false                           
                else:
                  - homeassistant.service:
                      service: cover.close_cover
                      data_template:
                        entity_id: cover.tane  
                  - globals.set:
                      id: blinds_tane_open
                      value: 'false'   
                  - lvgl.widget.update:
                      id: lvgl_keypad_button4
                      state: 
                        checked: true       

  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad5
    key: 5
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            - if:
                condition:
                  lambda: 'return id(blinds_lucy_open) == false;'
                then:               
                  - homeassistant.service:
                      service: cover.open_cover
                      data_template:
                        entity_id: cover.carrington_rd  
                  - homeassistant.service:
                      service: cover.open_cover
                      data_template:
                        entity_id: cover.darri_ave                          
                  - globals.set:
                      id: blinds_lucy_open
                      value: 'true'  
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: false                           
                else:
                  - homeassistant.service:
                      service: cover.close_cover
                      data_template:
                        entity_id: cover.carrington_rd  
                  - homeassistant.service:
                      service: cover.close_cover
                      data_template:
                        entity_id: cover.darri_ave                          
                  - globals.set:
                      id: blinds_lucy_open
                      value: 'false'   
                  - lvgl.widget.update:
                      id: lvgl_keypad_button5
                      state: 
                        checked: true   
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad6
    key: 6
    on_press:
      - logger.log: "******************************************"
      - if: 
          condition:
            lvgl.page.is_showing: pageC
          then:
            - logger.log:
                format: "button 6 value %.1f "
                args: [ 'id(lvgl_keypad_button6)' ]   
            - if:
                condition:
                  lambda: |-
                    if (id(lvgl_keypad_button6) > 0.0) {
                      return true;
                    } else {
                      return false;
                    }
                then:
                  - logger.log: "close blind"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: true  
                else:
                  - logger.log: "open blind"
                  - lvgl.widget.update:
                      id: lvgl_keypad_button6
                      state: 
                        checked: false   
            - logger.log:
                format: "button 6 value %.1f "
                args: [ 'id(lvgl_keypad_button6)' ]   
                  # - homeassistant.service:
                  #     service: cover.open_cover
                  #     data_template:
                  #       entity_id: cover.study  
      - logger.log: "******************************************"
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad7
    key: 7
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: kids_ac             
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad8
    key: 8
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: master_ac
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad9
    key: 9
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: pool_switch            
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad_star
    key: "*"
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: dehumidifier_switch
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad0
    key: 0
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: EV_switch   
      - if:
          condition:
            switch.is_on: EV_switch
          then:
            switch.turn_on: EV_override_switch
          else:
            switch.turn_off: EV_override_switch
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad_hash
    key: "#"
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: stairs_sign

