switch:
  - platform: homeassistant
    entity_id: switch.sonoff_10007724b9
    id: tanes_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button1
          state: 
            checked: true    
  - platform: homeassistant
    entity_id: switch.sonoff_10001adcce
    id: front_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button2
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button2
          state: 
            checked: true    
  - platform: homeassistant
    entity_id: switch.sonoff_10015acdb5
    id: kitchen_lights
    on_turn_on:
      - lvgl.widget.update:
          id: lvgl_keypad_button3
          state: 
            checked: false
    on_turn_off:
      - lvgl.widget.update:
          id: lvgl_keypad_button3
          state: 
            checked: true                

binary_sensor: 
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad1
    key: 1
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: tanes_lights
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad2
    key: 2
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: front_lights
  - platform: matrix_keypad
    keypad_id: keypad
    id: keypad3
    key: 3
    on_press:
      - if:
          condition:
            lvgl.page.is_showing: pageC
          then:
            switch.toggle: kitchen_lights

