globals:
  - id: g_powerprice
    type: float
    restore_value: no
    initial_value: '0.3115'
  - id: g_solarprice
    type: float
    restore_value: no
    initial_value: '0.07'    
  - id: g_poweredby
    type: std::string
    initial_value: ''      

sensor:
  - platform: homeassistant
    name: "Net Power state"
    id: net_power
    entity_id: sensor.net_power
    on_value:       
      then:
        - lvgl.indicator.update:
            id: power_needle
            value: !lambda "return x;"
    on_value_range:
      - above: 450
        then:
          - lvgl.label.update:
              id: cost_wh
              text: 
                format: "#00FF00 %.0fW, earning %.0f¢/ph"
                args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_solarprice)/10']
      - above: 0
        below: 450
        then:
          - lvgl.label.update:
              id: cost_wh
              text: 
                format: "#FFFF00 %.0fW, earning %.0f¢/ph"
                args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_solarprice)/10'] 
      - below: 0
        then:
          - lvgl.label.update:
              id: cost_wh
              text: 
                format: "#FF0000 %.0fW, costing $%.2fph"
                args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_powerprice)/1000']   
  
 
  - platform: homeassistant
    name: "Home Battery Power"
    id: home_battery_power
    entity_id: sensor.encharge_492334007623_power       
    on_value_range:
      - below: -10
        then:
          - globals.set:
              id: g_poweredby
              value: 'id(g_poweredby) + "Enphase (house) battery"'
          - lvgl.textarea.update:
              id: textarea_poweredby
              text: 
                format: "%s"
                args: [ 'id(g_poweredby).c_str()']                     

            
switch:
  - platform: homeassistant
    id: pool_switch
    entity_id: switch.sonoff_10001e7f40
    on_turn_on:
      - globals.set:
          id: g_poweredby
          value: 'id(g_poweredby) + "Pool"'
      - lvgl.textarea.update:
          id: textarea_poweredby
          text: 
            format: "%s"
            args: [ 'id(g_poweredby).c_str()']
    on_turn_off:
      - globals.set:
          id: g_poweredby
          value: 'id(g_poweredby) + "pool Off"'
      - lvgl.textarea.update:
          id: textarea_poweredby
          text: 
            format: "%s"
            args: [ 'id(g_poweredby).c_str()']    

