text_sensor:
  - platform: homeassistant
    name: "Alarm State"
    id: homeassistant_alarm
    entity_id: alarm_control_panel.home_alarm 
    on_value: 
      - lvgl.textarea.update:
          id: lbl_status
          text: !lambda 'return x.c_str();'         
      - if:
          condition:
            text_sensor.state:
              id: homeassistant_alarm
              state: 'disarmed'
          then:
            - lvgl.label.update:
                id: img_alarm_icon
                text: "\U000F009B" # disarmed
            - lvgl.textarea.update:                
                id: lbl_status
                text_color: col_green               
          else:
            - if:
                condition:
                  or:
                    - text_sensor.state:
                        id: homeassistant_alarm
                        state: 'arming'
                    - text_sensor.state:
                        id: homeassistant_alarm
                        state: 'pending'                        
                then:
                  - lvgl.label.update:
                      id: img_alarm_icon
                      text: "\U000F009A" # bell 
                  - lvgl.textarea.update:                
                      id: lbl_status
                      text_color: col_yellow              
                else:          
                  - if:
                      condition:
                        - text_sensor.state:
                            id: homeassistant_alarm
                            state: 'triggered'                              
                      then:
                        - lvgl.label.update:
                            id: img_alarm_icon
                            text: "\U000F009E" # bell-ring
                        - lvgl.textarea.update:                
                            id: lbl_status
                            text_color: col_red             
                      else:          
                        - if:
                            condition:
                              or:
                                - text_sensor.state:
                                    id: homeassistant_alarm
                                    state: 'armed_home'
                                - text_sensor.state:
                                    id: homeassistant_alarm
                                    state: 'armed_away'                        
                            then:
                              - lvgl.label.update:
                                  id: img_alarm_icon
                                  text: "\U000F009A" # bell 
                              - lvgl.textarea.update:                
                                  id: lbl_status
                                  text_color: col_orange             
                            else:          
                              - lvgl.label.update:
                                  id: img_alarm_icon
                                  text: "\U000F02D6" # help (?)
                              - lvgl.textarea.update:                
                                  id: lbl_status
                                  text_color: col_gray                

key_collector:
  - id: pincode_reader
    source_id: keypad
    end_keys: "#"
    end_key_required: true 
    clear_keys: "*"
    allowed_keys: "0123456789"
    timeout: 60s
    on_progress:
      - logger.log:
          format: "input progress: '%s', started by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)" ]
      - globals.set:
          id: g_keypad
          value: !lambda "return (x.c_str());"     
      - lvgl.textarea.update:
          id: txt_passcode
          text: !lambda "return (x);"  

    on_result:
      - logger.log:
          format: "input result: '%s', started by '%c', ended by '%c'"
          args: [ 'x.c_str()', "(start == 0 ? '~' : start)", "(end == 0 ? '~' : end)" ]
      - globals.set:
          id: g_keypad
          value: !lambda "return (x.c_str());" 
      - if:
          condition:
            # Checks if "homeassistant_alarm" has state "disarmed" arm else disarm
            text_sensor.state:
              id: homeassistant_alarm
              state: 'disarmed'   
          then:
            homeassistant.service: 
              service: script.alarm_arm
              data:
                code: !lambda "return (x.c_str());"   
          else:
            homeassistant.service: 
              service: script.alarm_disarm
              data:
                code: !lambda "return (x.c_str());"   
