sensor:
  # Tempreature
  - platform: homeassistant
    name: "Inside Temp"
    id: inside_temp
    entity_id: sensor.sensibo_Master_Bedroom_Temperature
    on_value:
      - lvgl.label.update:
          id: lbl_inside_temp
          text: 
            format: "%.1f°C"
            args: ['id(inside_temp).get_state()']
  - platform: homeassistant
    name: "Outside Temp"
    id: outside_temp
    entity_id: sensor.easyweatherv1_6_5_outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: lbl_outside_temp
          text: 
            format: "%.1f°C"
            args: ['id(outside_temp).get_state()']    

  # Forcast Icon

    
  - platform: homeassistant
    name: "Forecast Today Rain Chance"
    id: forecast_rain_chance_today
    entity_id: sensor.wahroonga_rain_chance_0
  - platform: homeassistant
    name: "Forecast Today Icon"
    id: forecast_icon_today
    entity_id: sensor.wahroonga_mdi_icon_0
  - platform: homeassistant
    name: "Forecast Today label"
    id: forecast_label_today
    entity_id: sensor.wahroonga_now_now_label       

text_sensor:
  - platform: homeassistant
    id: forecast_text_today
    entity_id: sensor.wahroonga_extended_text_0
    on_value:
      - lvgl.label.update:
          id: lbl_weather_longtext
          text: !lambda "return (x);"  