globals:
  - id: g_powerprice
    type: float
    restore_value: no
    initial_value: '0.3115'
  - id: g_solarprice
    type: float
    restore_value: no
    initial_value: '0.07'    

sensor:
  - platform: homeassistant
    name: "Net Power state"
    id: net_power
    entity_id: sensor.net_power
    on_value:       
      then:
        - lvgl.indicator.update:
            id: power_needle
            value: !lambda "return x;"
        - if:
            condition:
              lambda: "return (x > 450); "
            then:
              - lvgl.label.update:
                  id: cost_wh
                  text: 
                    format: "#00FF00 %.0fW, earning %.0f¢/ph"
                    args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_solarprice)/10']
            else:
              - if:
                  condition:
                    lambda: "return (x > 0); "
                  then:
                    - lvgl.label.update:
                        id: cost_wh
                        text: 
                          format: "#FFFF00 %.0fW, earning %.0f¢/ph"
                          args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_solarprice)/10'] 
                  else:           
                    - lvgl.label.update:
                        id: cost_wh
                        text: 
                          format: "#FF0000 %.0fW, costing $%.2fph"
                          args: [ 'id(net_power).get_state()',  'id(net_power).get_state()*id(g_powerprice)/1000']    